# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
import datetime
import pydantic
from typing import Any
import uuid


class Contact(pydantic.BaseModel):
    id: int
    uuid: uuid.UUID
    created_at: datetime.datetime
    event_id: int
    email: str
    phone_number: str
    address: str


class Event(pydantic.BaseModel):
    id: int
    uuid: uuid.UUID
    created_at: datetime.datetime
    payload: Any
